import test from 'node:test';
import assert from 'node:assert/strict';
import {
  GENERATOR_CONTRACT_VERSION,
  generateCompose,
  generateNginx,
  generateSystemd,
  generatorRegistry,
  outcomes,
} from '../dist/generators/index.js';

const inputs = {
  nginx: {domain: 'app.example.com', port: 3000, tls: true, websockets: true},
  compose: {service: 'web', image: 'nginx:stable', hostPort: 8080, containerPort: 80, restart: 'unless-stopped'},
  systemd: {service: 'myapp', description: 'My application', user: 'appuser', workdir: '/opt/app', executable: '/usr/bin/node', arguments: 'server.js'},
};

test('nginx preserves the legacy output shape and exact deterministic output', () => {
  const result = generateNginx(inputs.nginx);
  assert.equal(result.filename, 'app.example.com.conf');
  assert.equal(result.content, `# Generated by Forge — review before deployment.
# Place this map in nginx http context (once per installation).
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 80;
    server_name app.example.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app.example.com;
    ssl_certificate /etc/letsencrypt/live/app.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.example.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    server_tokens off;
    add_header X-Content-Type-Options nosniff always;
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
`);
  assert.deepEqual(generateNginx(inputs.nginx), generateNginx(structuredClone(inputs.nginx)));
});

test('compose preserves safe local binding and deterministic YAML quoting', () => {
  const result = generateCompose(inputs.compose);
  assert.equal(result.filename, 'compose.yaml');
  assert.equal(result.content, `# Generated by Forge — review before deployment.
services:
  web:
    image: "nginx:stable"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:8080:80"
    security_opt:
      - no-new-privileges:true
`);
  assert.deepEqual(generateCompose(inputs.compose), generateCompose({...inputs.compose}));
});

test('systemd preserves service output and hardening defaults', () => {
  const result = generateSystemd(inputs.systemd);
  assert.equal(result.filename, 'myapp.service');
  assert.match(result.content, /User=appuser/);
  assert.match(result.content, /ExecStart=\/usr\/bin\/node server\.js/);
  assert.match(result.content, /NoNewPrivileges=true/);
  assert.deepEqual(generateSystemd(inputs.systemd), generateSystemd({...inputs.systemd}));
});

test('all generators conform to the versioned contract and registry', () => {
  assert.equal(GENERATOR_CONTRACT_VERSION, '1.0');
  const definitions = generatorRegistry.list();
  assert.deepEqual(definitions.map(item => item.manifest.id), ['nginx', 'compose', 'systemd']);
  for (const definition of definitions) {
    assert.equal(definition.manifest.contractVersion, GENERATOR_CONTRACT_VERSION);
    assert.match(definition.manifest.generatorVersion, /^\d+\.\d+\.\d+$/);
    assert.equal(definition.manifest.inputSchema.additionalProperties, false);
    assert.ok(definition.manifest.inputSchema.fields.length > 0);
    assert.equal(definition.manifest.nativeValidation.available, false);
    assert.equal(typeof definition.validate, 'function');
    assert.equal(typeof definition.normalize, 'function');
    assert.equal(typeof definition.generate, 'function');
    assert.equal(typeof definition.staticValidate, 'function');
  }
});

test('successful output exposes artifacts, compatibility, warnings, provenance and honest validation states', () => {
  for (const id of ['nginx', 'compose', 'systemd']) {
    const outcome = outcomes[id](inputs[id]);
    assert.equal(outcome.ok, true);
    assert.equal(outcome.artifacts.length, 1);
    assert.equal(outcome.artifacts[0].role, 'primary');
    assert.ok(outcome.compatibility.length > 0);
    assert.ok(outcome.warnings.length >= 2);
    assert.deepEqual({input: outcome.validation.input.status, static: outcome.validation.static.status, native: outcome.validation.native.status}, {input: 'passed', static: 'passed', native: 'unavailable'});
    assert.equal(outcome.provenance.deterministic, true);
    assert.equal(outcome.provenance.generatorId, id);
  }
});

test('input failure is a structured state and prevents generation', () => {
  const outcome = outcomes.nginx({domain: 'invalid', port: 3000});
  assert.equal(outcome.ok, false);
  assert.equal(outcome.artifacts.length, 0);
  assert.deepEqual({input: outcome.validation.input.status, static: outcome.validation.static.status, native: outcome.validation.native.status}, {input: 'failed', static: 'not-run', native: 'unavailable'});
  assert.equal(outcome.diagnostics[0].stage, 'input');
});

test('nginx rejects directive injection, malformed domains and invalid ports', () => {
  assert.throws(() => generateNginx({domain: 'site.test;return 200', port: 3000}), /domain/i);
  assert.throws(() => generateNginx({domain: 'site..test', port: 3000}), /domain/i);
  assert.throws(() => generateNginx({domain: 'site.test', port: 99999}), /port/i);
  assert.throws(() => generateNginx({...inputs.nginx, injected: 'value'}), /Unsupported input field/i);
});

test('compose rejects YAML injection, image injection and invalid enums', () => {
  assert.throws(() => generateCompose({...inputs.compose, service: 'web\nextra'}), /Service name/i);
  assert.throws(() => generateCompose({...inputs.compose, image: 'nginx:latest\nprivileged: true'}), /Image/i);
  assert.throws(() => generateCompose({...inputs.compose, restart: 'never'}), /Restart policy/i);
  assert.throws(() => generateCompose({...inputs.compose, hostPort: '8080:9000'}), /Host port/i);
});

test('systemd rejects directive, specifier, traversal and shell injection', () => {
  assert.throws(() => generateSystemd({...inputs.systemd, arguments: 'server.js\nExecStart=/bin/sh'}), /Arguments/i);
  assert.throws(() => generateSystemd({...inputs.systemd, arguments: 'server.js; rm -rf /'}), /Arguments/i);
  assert.throws(() => generateSystemd({...inputs.systemd, arguments: '%h/secret'}), /Arguments/i);
  assert.throws(() => generateSystemd({...inputs.systemd, workdir: '/opt/../root'}), /Working directory/i);
  assert.throws(() => generateSystemd({...inputs.systemd, description: 'hello\n[Service]'}), /Description/i);
});

test('optional legacy defaults remain backward compatible', () => {
  assert.match(generateCompose({service: 'web', image: 'nginx:stable', hostPort: 8080, containerPort: 80}).content, /restart: "unless-stopped"/);
  assert.match(generateSystemd({service: 'myapp', user: 'appuser', workdir: '/opt/app', executable: '/usr/bin/node'}).content, /Description=Managed application/);
  assert.doesNotMatch(generateNginx({domain: 'app.example.com', port: 3000}).content, /listen 443/);
});
