import {GeneratorInputError} from '../core/errors.js';
import {objectInput, rejectUnknownKeys, safeImageReference, safeName, safePort} from '../core/validation.js';
import type {Diagnostic, GeneratorDefinition, OutputArtifact} from '../core/types.js';

const restartPolicies = ['no', 'always', 'unless-stopped', 'on-failure'] as const;
type RestartPolicy = typeof restartPolicies[number];

interface ComposeInput {
  readonly service: string;
  readonly image: string;
  readonly hostPort: number;
  readonly containerPort: number;
  readonly restart: RestartPolicy;
}

type ComposeNormalized = ComposeInput;

function yamlString(value: string): string {
  return JSON.stringify(value);
}

export const composeGenerator: GeneratorDefinition<ComposeInput, ComposeNormalized> = {
  manifest: {
    id: 'compose',
    displayName: 'Docker Compose service',
    contractVersion: '1.0',
    generatorVersion: '1.0.0',
    inputSchema: {
      version: '1.0',
      additionalProperties: false,
      fields: [
        {name: 'service', type: 'string', required: true, description: 'Compose service name.'},
        {name: 'image', type: 'string', required: true, description: 'Container image reference.'},
        {name: 'hostPort', type: 'integer', required: true, description: 'Loopback host port.'},
        {name: 'containerPort', type: 'integer', required: true, description: 'Container port.'},
        {name: 'restart', type: 'enum', required: false, default: 'unless-stopped', values: restartPolicies, description: 'Container restart policy.'},
      ],
    },
    compatibility: [{technology: 'Docker Compose', versions: 'Compose Specification / Docker Compose v2', notes: ['Emits the modern Compose Specification without a top-level version key.']}],
    nativeValidation: {available: false, tool: 'docker compose config -q', reason: 'Schema-checked in-browser; Docker Compose CLI not run here.'},
  },
  validate(input: unknown): ComposeInput {
    const record = objectInput(input);
    rejectUnknownKeys(record, ['service', 'image', 'hostPort', 'containerPort', 'restart']);
    const restart = record.restart === undefined ? 'unless-stopped' : String(record.restart);
    if (!restartPolicies.includes(restart as RestartPolicy)) throw new GeneratorInputError('input.restart', 'Restart policy must be one of: no, always, unless-stopped, on-failure.');
    return {
      service: safeName(record.service, 'Service name'),
      image: safeImageReference(record.image),
      hostPort: safePort(record.hostPort, 'Host port'),
      containerPort: safePort(record.containerPort, 'Container port'),
      restart: restart as RestartPolicy,
    };
  },
  normalize(input: ComposeInput): ComposeNormalized {
    return input;
  },
  generate(input: ComposeNormalized) {
    const content = `# Generated by Forge — review before deployment.\nservices:\n  ${input.service}:\n    image: ${yamlString(input.image)}\n    restart: ${yamlString(input.restart)}\n    ports:\n      - ${yamlString(`127.0.0.1:${input.hostPort}:${input.containerPort}`)}\n    security_opt:\n      - no-new-privileges:true\n`;
    return {
      artifacts: [{id: 'compose-file', filename: 'compose.yaml', mediaType: 'application/yaml', role: 'primary', content}],
      diagnostics: [{code: 'compose.loopback', severity: 'warning', stage: 'static', message: 'Ports bind to loopback by default, not to all network interfaces.'}],
      deploymentSteps: [
        'Replace example image with a pinned version or digest.',
        'Use an external secret store or a non-committed .env file; never put credentials in this file.',
        'Run docker compose config -q to validate, then docker compose up -d.',
        'Verify docker compose ps and application health; to roll back, restore the previous compose file and image.',
      ],
    };
  },
  staticValidate(artifacts: readonly OutputArtifact[]): readonly Diagnostic[] {
    const content = artifacts[0]?.content ?? '';
    return content.includes('services:\n') && content.includes('127.0.0.1:') && content.includes('no-new-privileges:true')
      ? []
      : [{code: 'compose.structure', severity: 'error', stage: 'static', message: 'Required Compose structure or security defaults are missing.'}];
  },
};
