const fail = message => { throw new Error(message); };
const name = (value, label='Name') => {
  const v=String(value??'').trim();
  if(!/^[a-zA-Z][a-zA-Z0-9_-]{0,62}$/.test(v)) fail(`${label} must start with a letter and contain only letters, numbers, _ or - (max 63).`);
  return v;
};
const port = (value,label='Port') => {
  const v=String(value??'').trim();
  if(!/^\d+$/.test(v)||Number(v)<1||Number(v)>65535) fail(`${label} must be between 1 and 65535.`);
  return Number(v);
};
const domain = value => {
  const v=String(value??'').trim().toLowerCase();
  if(v.length>253||!v.includes('.')||!v.split('.').every(x=>/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(x))) fail('Enter a valid fully qualified domain name.');
  return v;
};
const bool = value => value === true;
const safePath = (value,label='Path') => {
  const v=String(value??'').trim();
  if(!/^\/[a-zA-Z0-9_./-]*$/.test(v)||v.includes('..')) fail(`${label} must be an absolute path without whitespace or traversal.`);
  return v;
};
const image = value => {
  const v=String(value??'').trim();
  if(!/^[a-zA-Z0-9][a-zA-Z0-9._\/:@-]{0,199}$/.test(v)) fail('Image must be a valid image reference without whitespace or shell characters.');
  return v;
};
function yamlStr(value){ return JSON.stringify(String(value)); }
export function generateNginx(input){
  const host=domain(input.domain), target=port(input.port), tls=bool(input.tls), websockets=bool(input.websockets);
  const proxy=`    location / {\n        proxy_pass http://127.0.0.1:${target};\n        proxy_http_version 1.1;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;${websockets?'\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection $connection_upgrade;':''}\n    }`;
  const map=websockets?`# Place this map in nginx http context (once per installation).\nmap $http_upgrade $connection_upgrade {\n    default upgrade;\n    '' close;\n}\n\n`:'';
  const plain=`server {\n    listen 80;\n    server_name ${host};\n${tls?'    return 301 https://$host$request_uri;':proxy}\n}`;
  const secure=tls?`\n\nserver {\n    listen 443 ssl;\n    server_name ${host};\n    ssl_certificate /etc/letsencrypt/live/${host}/fullchain.pem;\n    ssl_certificate_key /etc/letsencrypt/live/${host}/privkey.pem;\n    ssl_protocols TLSv1.2 TLSv1.3;\n    server_tokens off;\n    add_header X-Content-Type-Options nosniff always;\n${proxy}\n}`:'';
  return {filename:`${host}.conf`,content:`# Generated by Forge — review before deployment.\n${map}${plain}${secure}\n`,steps:[`Ensure the application listens on 127.0.0.1:${target}.`,...(tls?[`Provision TLS certificate files for ${host} before nginx -t.`]:[]),...(websockets?['Move the map directive to the http context if you use a separate sites-enabled file; define it only once.']:[]),'Back up the existing configuration.','Run sudo nginx -t; only after success run sudo systemctl reload nginx.','If the reload causes trouble, restore the previous file and test/reload again.'],checks:['Configuration is schema-checked in-browser, NOT verified by an Nginx parser.','If Nginx is behind another proxy, review real-IP and forwarded-header trust settings.']};
}
export function generateCompose(input){
  const service=name(input.service,'Service name'), img=image(input.image), host=port(input.hostPort,'Host port'), container=port(input.containerPort,'Container port');
  const restart=['no','always','unless-stopped','on-failure'].includes(input.restart)?input.restart:'unless-stopped';
  const content=`# Generated by Forge — review before deployment.\nservices:\n  ${service}:\n    image: ${yamlStr(img)}\n    restart: ${yamlStr(restart)}\n    ports:\n      - ${yamlStr(`127.0.0.1:${host}:${container}`)}\n    security_opt:\n      - no-new-privileges:true\n`;
  return {filename:'compose.yaml',content,steps:['Replace example image with a pinned version or digest.','Use an external secret store or a non-committed .env file; never put credentials in this file.','Run docker compose config -q to validate, then docker compose up -d.','Verify docker compose ps and application health; to roll back, restore the previous compose file and image.'],checks:['Schema-checked in-browser; Docker Compose CLI not run here.','Ports bind to loopback by default, not to all network interfaces.']};
}
export function generateSystemd(input){
  const service=name(input.service,'Service name'), user=name(input.user,'Linux user'), workdir=safePath(input.workdir,'Working directory'), exec=safePath(input.executable,'Executable');
  const args=String(input.arguments??'').trim();
  if(/[\n\r%\\]/.test(args)||/[;|&<>`$]/.test(args)) fail('Arguments contain unsupported shell or systemd special characters; edit manually after review.');
  const description=String(input.description??'Managed application').trim();
  if(!/^[a-zA-Z0-9 _.,()-]{1,100}$/.test(description)) fail('Description has unsupported characters.');
  const content=`# Generated by Forge — review before deployment.\n[Unit]\nDescription=${description}\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nUser=${user}\nWorkingDirectory=${workdir}\nExecStart=${exec}${args?' '+args:''}\nRestart=on-failure\nRestartSec=5s\nNoNewPrivileges=true\nPrivateTmp=true\n\n[Install]\nWantedBy=multi-user.target\n`;
  return {filename:`${service}.service`,content,steps:[`Ensure the ${user} user, ${workdir} directory, and ${exec} executable exist.`,`Back up any previous ${service}.service unit.`,`Copy to /etc/systemd/system/${service}.service.`,`Run sudo systemd-analyze verify /etc/systemd/system/${service}.service.`,`Run sudo systemctl daemon-reload && sudo systemctl enable --now ${service}.service.`,`Inspect sudo systemctl status ${service} and journalctl -u ${service} -n 100.`],checks:['Schema-checked in-browser; systemd-analyze not run here.','Review filesystem permissions, service arguments, and required environment separately.']};
}
export const generators={nginx:generateNginx,compose:generateCompose,systemd:generateSystemd};
