import {objectInput, rejectUnknownKeys, safeBoolean, safeDomain, safePort} from '../core/validation.js';
import type {Diagnostic, GeneratorDefinition, OutputArtifact} from '../core/types.js';

interface NginxInput {
  readonly domain: string;
  readonly port: number;
  readonly tls: boolean;
  readonly websockets: boolean;
}

type NginxNormalized = NginxInput;

const warning = (code: string, message: string): Diagnostic => ({code, message, severity: 'warning', stage: 'static'});

export const nginxGenerator: GeneratorDefinition<NginxInput, NginxNormalized> = {
  manifest: {
    id: 'nginx',
    displayName: 'Nginx reverse proxy',
    contractVersion: '1.0',
    generatorVersion: '1.0.0',
    inputSchema: {
      version: '1.0',
      additionalProperties: false,
      fields: [
        {name: 'domain', type: 'string', required: true, description: 'Fully qualified public domain name.'},
        {name: 'port', type: 'integer', required: true, description: 'Loopback application port.'},
        {name: 'tls', type: 'boolean', required: false, default: false, description: 'Add HTTPS redirect and TLS server.'},
        {name: 'websockets', type: 'boolean', required: false, default: false, description: 'Add WebSocket upgrade headers.'},
      ],
    },
    compatibility: [{technology: 'Nginx', versions: '1.18+', platform: 'Linux', notes: ['The WebSocket map belongs in the http context.', 'TLS paths assume Certbot-compatible certificate layout.']}],
    nativeValidation: {available: false, tool: 'nginx -t', reason: 'Configuration is schema-checked in-browser, NOT verified by an Nginx parser.'},
  },
  validate(input: unknown): NginxInput {
    const record = objectInput(input);
    rejectUnknownKeys(record, ['domain', 'port', 'tls', 'websockets']);
    return {domain: safeDomain(record.domain), port: safePort(record.port), tls: safeBoolean(record.tls), websockets: safeBoolean(record.websockets)};
  },
  normalize(input: NginxInput): NginxNormalized {
    return input;
  },
  generate(input: NginxNormalized) {
    const {domain, port, tls, websockets} = input;
    const proxy = `    location / {\n        proxy_pass http://127.0.0.1:${port};\n        proxy_http_version 1.1;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;${websockets ? '\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection $connection_upgrade;' : ''}\n    }`;
    const map = websockets ? `# Place this map in nginx http context (once per installation).\nmap $http_upgrade $connection_upgrade {\n    default upgrade;\n    '' close;\n}\n\n` : '';
    const plain = `server {\n    listen 80;\n    server_name ${domain};\n${tls ? '    return 301 https://$host$request_uri;' : proxy}\n}`;
    const secure = tls ? `\n\nserver {\n    listen 443 ssl;\n    server_name ${domain};\n    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;\n    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;\n    ssl_protocols TLSv1.2 TLSv1.3;\n    server_tokens off;\n    add_header X-Content-Type-Options nosniff always;\n${proxy}\n}` : '';
    return {
      artifacts: [{id: 'nginx-site', filename: `${domain}.conf`, mediaType: 'text/nginx', role: 'primary', content: `# Generated by Forge — review before deployment.\n${map}${plain}${secure}\n`}],
      diagnostics: [warning('nginx.forwarded-headers', 'If Nginx is behind another proxy, review real-IP and forwarded-header trust settings.')],
      deploymentSteps: [
        `Ensure the application listens on 127.0.0.1:${port}.`,
        ...(tls ? [`Provision TLS certificate files for ${domain} before nginx -t.`] : []),
        ...(websockets ? ['Move the map directive to the http context if you use a separate sites-enabled file; define it only once.'] : []),
        'Back up the existing configuration.',
        'Run sudo nginx -t; only after success run sudo systemctl reload nginx.',
        'If the reload causes trouble, restore the previous file and test/reload again.',
      ],
    };
  },
  staticValidate(artifacts: readonly OutputArtifact[]): readonly Diagnostic[] {
    const content = artifacts[0]?.content ?? '';
    return content.includes('server_name ') && content.includes('proxy_pass http://127.0.0.1:')
      ? []
      : [{code: 'nginx.structure', severity: 'error', stage: 'static', message: 'Required Nginx server or proxy directives are missing.'}];
  },
};
