import {GeneratorInputError} from '../core/errors.js';
import {objectInput, rejectUnknownKeys, safeAbsolutePath, safeName, safeSystemdArguments} from '../core/validation.js';
import type {Diagnostic, GeneratorDefinition, OutputArtifact} from '../core/types.js';

interface SystemdInput {
  readonly service: string;
  readonly description: string;
  readonly user: string;
  readonly workdir: string;
  readonly executable: string;
  readonly arguments: string;
}

type SystemdNormalized = SystemdInput;

function safeDescription(value: unknown): string {
  const normalized = String(value ?? 'Managed application').trim();
  if (!/^[a-zA-Z0-9 _.,()-]{1,100}$/.test(normalized)) throw new GeneratorInputError('input.description', 'Description has unsupported characters.');
  return normalized;
}

export const systemdGenerator: GeneratorDefinition<SystemdInput, SystemdNormalized> = {
  manifest: {
    id: 'systemd',
    displayName: 'systemd service',
    contractVersion: '1.0',
    generatorVersion: '1.0.0',
    inputSchema: {
      version: '1.0',
      additionalProperties: false,
      fields: [
        {name: 'service', type: 'string', required: true, description: 'Unit base name.'},
        {name: 'description', type: 'string', required: false, default: 'Managed application', description: 'Human-readable unit description.'},
        {name: 'user', type: 'string', required: true, description: 'Unprivileged Linux account.'},
        {name: 'workdir', type: 'string', required: true, description: 'Absolute working directory.'},
        {name: 'executable', type: 'string', required: true, description: 'Absolute executable path.'},
        {name: 'arguments', type: 'string', required: false, default: '', description: 'Space-separated literal arguments.'},
      ],
    },
    compatibility: [{technology: 'systemd', versions: 'v232+', platform: 'Linux', notes: ['Uses common service hardening directives available in supported enterprise distributions.']}],
    nativeValidation: {available: false, tool: 'systemd-analyze verify', reason: 'Schema-checked in-browser; systemd-analyze not run here.'},
  },
  validate(input: unknown): SystemdInput {
    const record = objectInput(input);
    rejectUnknownKeys(record, ['service', 'description', 'user', 'workdir', 'executable', 'arguments']);
    return {
      service: safeName(record.service, 'Service name'),
      description: safeDescription(record.description),
      user: safeName(record.user, 'Linux user'),
      workdir: safeAbsolutePath(record.workdir, 'Working directory'),
      executable: safeAbsolutePath(record.executable, 'Executable'),
      arguments: safeSystemdArguments(record.arguments),
    };
  },
  normalize(input: SystemdInput): SystemdNormalized {
    return input;
  },
  generate(input: SystemdNormalized) {
    const content = `# Generated by Forge — review before deployment.\n[Unit]\nDescription=${input.description}\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nUser=${input.user}\nWorkingDirectory=${input.workdir}\nExecStart=${input.executable}${input.arguments ? ` ${input.arguments}` : ''}\nRestart=on-failure\nRestartSec=5s\nNoNewPrivileges=true\nPrivateTmp=true\n\n[Install]\nWantedBy=multi-user.target\n`;
    return {
      artifacts: [{id: 'systemd-unit', filename: `${input.service}.service`, mediaType: 'text/plain', role: 'primary', content}],
      diagnostics: [{code: 'systemd.permissions', severity: 'warning', stage: 'static', message: 'Review filesystem permissions, service arguments, and required environment separately.'}],
      deploymentSteps: [
        `Ensure the ${input.user} user, ${input.workdir} directory, and ${input.executable} executable exist.`,
        `Back up any previous ${input.service}.service unit.`,
        `Copy to /etc/systemd/system/${input.service}.service.`,
        `Run sudo systemd-analyze verify /etc/systemd/system/${input.service}.service.`,
        `Run sudo systemctl daemon-reload && sudo systemctl enable --now ${input.service}.service.`,
        `Inspect sudo systemctl status ${input.service} and journalctl -u ${input.service} -n 100.`,
      ],
    };
  },
  staticValidate(artifacts: readonly OutputArtifact[]): readonly Diagnostic[] {
    const content = artifacts[0]?.content ?? '';
    return content.includes('[Service]\n') && content.includes('NoNewPrivileges=true') && content.includes('ExecStart=/')
      ? []
      : [{code: 'systemd.structure', severity: 'error', stage: 'static', message: 'Required systemd service or hardening directives are missing.'}];
  },
};
