import {generators} from './generators/index.js';
const $=id=>document.getElementById(id);
const options={
 nginx:{title:'Nginx reverse proxy',subtitle:'Configure your domain and upstream',fields:[['domain','Domain name','text','app.example.com'],['port','Application port','number','3000'],['tls','Enable HTTPS redirect + TLS server','checkbox',true],['websockets','WebSocket upgrade support','checkbox',false]]},
 compose:{title:'Docker Compose service',subtitle:'Generate a loopback-bound container service',fields:[['service','Service name','text','web'],['image','Container image','text','nginx:stable'],['hostPort','Host port','number','8080'],['containerPort','Container port','number','80'],['restart','Restart policy','select','unless-stopped']]},
 systemd:{title:'systemd service',subtitle:'Create a managed Linux service unit',fields:[['service','Service name','text','myapp'],['description','Description','text','My application'],['user','Linux user','text','appuser'],['workdir','Working directory','text','/opt/myapp'],['executable','Executable path','text','/usr/bin/node'],['arguments','Arguments (optional)','text','server.js']]}
};
let selected='nginx',result=null;
function render(){const o=options[selected];$('heading').textContent=o.title;$('subtitle').textContent=o.subtitle;$('crumb').textContent=o.title.split(' ')[0];$('generator-form').replaceChildren();for(const [id,label,type,value] of o.fields){const wrap=document.createElement('label');wrap.className=type==='checkbox'?'check':'field';const span=document.createElement('span');span.textContent=label;const input=document.createElement(type==='select'?'select':'input');input.name=id;input.id=id;if(type==='checkbox')input.type='checkbox';else if(type!=='select')input.type=type;if(type==='checkbox')input.checked=value;else if(type==='select'){for(const s of ['unless-stopped','always','no','on-failure']){const opt=document.createElement('option');opt.value=s;opt.textContent=s;input.append(opt);}input.value=value;}else input.value=value;if(type==='checkbox'){wrap.append(input,span)}else wrap.append(span,input);$('generator-form').append(wrap);}document.querySelectorAll('[data-type]').forEach(x=>x.classList.toggle('active',x.dataset.type===selected));generate();}
function read(){const data={};new FormData($('generator-form')).forEach((v,k)=>data[k]=v);for(const [id,,type] of options[selected].fields)if(type==='checkbox')data[id]=$(id).checked;return data;}
function generate(){try{result=generators[selected](read());$('output').textContent=result.content;$('filename').textContent=result.filename;$('status').textContent='Generated';$('status').classList.remove('error');$('message').textContent='';$('steps').replaceChildren();for(const step of result.steps){const li=document.createElement('li');li.textContent=step;$('steps').append(li);}$('checks').replaceChildren();for(const check of result.checks){const p=document.createElement('p');p.textContent='⚠ '+check;$('checks').append(p);}}catch(e){result=null;$('status').textContent='Invalid input';$('status').classList.add('error');$('message').textContent=e.message;$('output').textContent='Fix the input values to generate a configuration.';$('steps').replaceChildren();$('checks').replaceChildren();}}
document.querySelectorAll('[data-type]').forEach(el=>el.addEventListener('click',()=>{selected=el.dataset.type;render();}));$('generate').addEventListener('click',generate);$('copy').addEventListener('click',async()=>{if(!result)return;try{await navigator.clipboard.writeText(result.content);$('copy').textContent='Copied ✓';setTimeout(()=>$('copy').textContent='Copy code',1300)}catch{$('message').textContent='Clipboard unavailable; select the preview text manually.'}});$('download').addEventListener('click',()=>{if(!result)return;const url=URL.createObjectURL(new Blob([result.content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=result.filename;a.click();URL.revokeObjectURL(url);});render();
